### ISSUE TITLE
Premium Security Content Import

### ISSUE THREAD

**Issue by lansami** [hlxsites/bitdefender#203]
Content import in the premium-security document from https://www.bitdefender.com.au/solutions/premium-security.html

**Comment by nsdere** [comment]
- Hero Section
1. Background image should change
2. Premium security why uppercase?
3. Multi device should be smaller
4. Hero content should be smaller by means of width
5. Space between the last green tick point line and note in bold.
6. Background image not seeing below 989px, this is not true for original page
- Product Cards Section
8. Product card values and the content
9. Product card title and text sizing
- Awards Section
11. Awards section is displayed as column and not complete for 989
- CTA Column Section
13. CTA column title sizing and text coloring
- Column section
15. Bitdefender premium security plus bullet points
- Product Features Column
17. In-line icons and the column texts for the best way to protect your identity online part
- Product Features Tabs
19. Product features should be displayed 3 columns side by side for 992?
- Comparing Products
21. Titles of comparing products are so big, terms of use link for the first column, padding less so that it wont be 3 rows for the text
- FAQ
23. FAQ question headers a big bigger -> 22px
